In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import regex as re
import wikipedia as wp

pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

# 2018 Free Agent Scraping

In [67]:
html = wp.page("List of 2018–19 NBA season transactions").html().encode("UTF-8")
FA2018 = pd.read_html(html)[5]
FA2018.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Derrick Jones Jr.**** (RFA),July 1,Miami Heat,[64],NaN
2,Thomas Bryant,July 2,Washington Wizards(Claimed off waivers),Los Angeles Lakers(Waived on June 30),[65]
3,Brad Wanamaker,Boston Celtics,FenerbahÃ§e DoÄuÅ (Turkey),[66],NaN
4,Derrick Rose,July 4,Minnesota Timberwolves,[67],NaN

In [70]:
FA2018 = FA2018[:109]

In [75]:
FA2018[0] = FA2018[0].str.replace('*','')
FA2018[0] = FA2018[0].str.replace('(RFA)','')
FA2018[0] = FA2018[0].str.replace(')','')
FA2018[0] = FA2018[0].str.replace('(','')
FA2018[0] = FA2018[0].str.replace('[','')
FA2018[0] = FA2018[0].str.replace('v]','')
FA2018[0] = FA2018[0].str.replace('e]','')
FA2018[0] = FA2018[0].str.replace('P. J.', 'P.J.')
FA2018[0] = FA2018[0].str.replace('J. J.', 'J.J.')
FA2018[0] = FA2018[0].str.replace('C. J.', 'C.J.')
FA2018[0] = FA2018[0].str.replace('K. J.', 'K.J.')
FA2018[0] = FA2018[0].str.replace('L. J.', 'L.J.')
FA2018[0] = FA2018[0].str.replace('V. J.', 'V.J.')
FA2018[0] = FA2018[0].str.replace('ć', 'c')
FA2018[0] = FA2018[0].str.replace('ê', 'e')
FA2018[0] = FA2018[0].str.replace('í', 'i')
FA2018[0] = FA2018[0].str.replace('š', 's')
FA2018[0] = FA2018[0].str.replace('é', 'e')
FA2018[0] = FA2018[0].str.replace('İ', 'I')
FA2018[0] = FA2018[0].str.replace('ž', 'z')
FA2018[0] = FA2018[0].str.replace('Ä', 'c')
FA2018[0] = FA2018[0].str.replace('ó','o')
FA2018[0] = FA2018[0].str.replace('Ã©', 'e')
FA2018[0] = FA2018[0].str.replace('Ã³', 'o')
FA2018[0] = FA2018[0].str.replace('Ä°', 'I')
FA2018[0] = FA2018[0].str.replace('Ä', 'a')
FA2018 = FA2018[FA2018[2].str.contains('Turkey') == False]
FA2018 = FA2018[FA2018[2].str.contains('Estonia') == False]
FA2018 = FA2018[FA2018[2].str.contains('Undrafted') == False]
FA2018 = FA2018[FA2018[3].str.contains('Undrafted') == False]
FA2018 = FA2018[FA2018[2].str.contains('Russia') == False]
FA2018 = FA2018[FA2018[2].str.contains('China') == False]
FA2018 = FA2018[FA2018[2].str.contains('Lebanon') == False]
FA2018 = FA2018[FA2018[3].str.contains('Belgium') == False]

In [76]:
FA2018

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Derrick Jones Jr.,July 1,Miami Heat,[64],NaN
2,Thomas Bryant,July 2,Washington Wizards(Claimed off waivers),Los Angeles Lakers(Waived on June 30),[65]
4,Derrick Rose,July 4,Minnesota Timberwolves,[67],NaN
6,Nik Stauskas,Portland Trail Blazers,Brooklyn Nets,[69],NaN
7,Trevor Ariza,July 6,Phoenix Suns,Houston Rockets,[70]
10,DeMarcus Cousins,Golden State Warriors,New Orleans Pelicans,[73],NaN
11,Seth Curry,Portland Trail Blazers,Dallas Mavericks,[74],NaN
12,Tyreke Evans,Indiana Pacers,Memphis Grizzlies,[75],NaN
17,Mario Hezonja,New York Knicks,Orlando Magic,[79],NaN
18,DeAndre Jordan,Dallas Mavericks,Los Angeles Clippers,[80],NaN
20,Doug McDermott,Indiana Pacers,Dallas Mavericks,[75],NaN
22,Nerlens Noel,Oklahoma City Thunder,Dallas Mavericks,[82],NaN
25,Rajon Rondo,Los Angeles Lakers,New Orleans Pelicans,[84],NaN
27,Aron Baynes,July 7,Boston Celtics,[86],NaN
28,Jose Calderon,Detroit Pistons,Cleveland Cavaliers,[87],NaN
29,Michael Carter-Williams,Houston Rockets,Charlotte Hornets,[88],NaN
32,Glenn Robinson,Detroit Pistons,Indiana Pacers,[87],NaN
33,Zach LaVine,July 8,Chicago Bulls,[91],NaN
35,Kyle Anderson,July 9,Memphis Grizzlies,San Antonio Spurs,[93]
39,LeBron James,Los Angeles Lakers,Cleveland Cavaliers,[97],NaN
41,Kyle O'Quinn,Indiana Pacers,New York Knicks,[99],NaN
42,Elfrid Payton,New Orleans Pelicans,Phoenix Suns,[100],NaN
44,Mike Scott,Los Angeles Clippers,Washington Wizards,[101],NaN
45,Anthony Tolliver,Minnesota Timberwolves,Detroit Pistons,[102],NaN
46,Torrey Craig,July 10,Denver Nuggets,[103],NaN
48,Jeff Green,Washington Wizards,Cleveland Cavaliers,[105],NaN
50,JaVale McGee,Los Angeles Lakers,Golden State Warriors,[107],NaN
52,Davis Bertans,July 11,San Antonio Spurs,[109],NaN
53,Omri Casspi,Memphis Grizzlies,Golden State Warriors(Waived on April 7),[110],NaN
55,Raymond Felton,July 12,Oklahoma City Thunder,[112],NaN
56,Dwight Howard,Washington Wizards,Brooklyn Nets(Waived on July 6),[113],NaN
57,Jonas Jerebko,Golden State Warriors,Utah Jazz(Waived on July 7),[114],NaN
59,Wayne Ellington,July 13,Miami Heat,[116],NaN
60,James Ennis,Houston Rockets,Detroit Pistons,[117],NaN
62,Jabari Parker,July 14,Chicago Bulls,Milwaukee Bucks,[119]
63,Zaza Pachulia,July 15,Detroit Pistons,Golden State Warriors,[120]
64,Ersan Ilyasova,July 16,Milwaukee Bucks,Philadelphia 76ers,[121]
66,Isaiah Thomas,Denver Nuggets,Los Angeles Lakers,[123],NaN
67,Brook Lopez,July 17,Milwaukee Bucks,Los Angeles Lakers,[124]
68,Shabazz Napier,Brooklyn Nets,Portland Trail Blazers,[125],NaN
70,Antonio Blakeney,July 19,Chicago Bulls(previously on a two-way contract),[127],NaN
72,Channing Frye,Cleveland Cavaliers,Los Angeles Lakers,[129],NaN
73,Luc Mbah a Moute,Los Angeles Clippers,Houston Rockets,[130],NaN
75,Marco Belinelli,July 20,San Antonio Spurs,Philadelphia 76ers,[132]
76,Chris Boucher,Toronto Raptors,Golden State Warriors(previously on a two-way ...,[133],NaN
78,Dante Cunningham,San Antonio Spurs,Brooklyn Nets,[134],NaN
80,Nemanja Bjelica,July 21,Sacramento Kings,Minnesota Timberwolves,[136]
82,Michael Beasley,July 23,Los Angeles Lakers,New York Knicks,[138]
83,Antonius Cleveland,Chicago Bulls(Claimed off waivers),Atlanta Hawks(Waived on July 21),[139],NaN
84,Ed Davis,Brooklyn Nets,Portland Trail Blazers,[140],NaN
86,Yogi Ferrell,Sacramento Kings,Dallas Mavericks,[142],NaN
88,Tony Parker,Charlotte Hornets,San Antonio Spurs,[144],NaN
92,Noah Vonleh,New York Knicks,Chicago Bulls,[148],NaN
94,Kadeem Allen,July 25,New York Knicks,Boston Celtics(previously on a two-way contract),[149]
100,Clint Capela,July 27,Houston Rockets,[153],NaN
102,Troy Williams,New Orleans Pelicans,New York Knicks(Waived on July 16),[155],NaN
103,Treveon Graham,July 30,Brooklyn Nets,Charlotte Hornets,[156]
104,Ryan Arcidiacono,July 31,Chicago Bulls,[157],NaN
108,Pat Connaughton,August 1,Milwaukee Bucks,Portland Trail Blazers,[160]

In [77]:
FA2018 = FA2018[0]

In [80]:
FA2018

0                       Player
1           Derrick Jones Jr.
2                Thomas Bryant
4                 Derrick Rose
6                 Nik Stauskas
7                 Trevor Ariza
10            DeMarcus Cousins
11                  Seth Curry
12                Tyreke Evans
17               Mario Hezonja
18              DeAndre Jordan
20              Doug McDermott
22                Nerlens Noel
25                 Rajon Rondo
27                 Aron Baynes
28               Jose Calderon
29     Michael Carter-Williams
32              Glenn Robinson
33                Zach LaVine
35              Kyle Anderson
39                LeBron James
41                Kyle O'Quinn
42               Elfrid Payton
44                  Mike Scott
45            Anthony Tolliver
46               Torrey Craig
48                  Jeff Green
50                JaVale McGee
52              Davis Bertans
53                 Omri Casspi
55              Raymond Felton
56               Dwight Howard
57               Jonas Jerebko
59             Wayne Ellington
60                 James Ennis
62               Jabari Parker
63               Zaza Pachulia
64              Ersan Ilyasova
66               Isaiah Thomas
67                 Brook Lopez
68              Shabazz Napier
70            Antonio Blakeney
72               Channing Frye
73            Luc Mbah a Moute
75             Marco Belinelli
76               Chris Boucher
78            Dante Cunningham
80             Nemanja Bjelica
82             Michael Beasley
83          Antonius Cleveland
84                    Ed Davis
86                Yogi Ferrell
88                 Tony Parker
92                 Noah Vonleh
94                Kadeem Allen
100              Clint Capela
102              Troy Williams
103             Treveon Graham
104           Ryan Arcidiacono
108            Pat Connaughton
Name: 0, dtype: object

In [79]:
FA2018.to_csv('2018_Free_Agents.csv', index=False)

# 2017 Free Agent Scraping

In [7]:
html = wp.page("List of 2017–18 NBA season transactions").html().encode("UTF-8")
FA2017 = pd.read_html(html)[6]
FA2017.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Wayne Selden Jr.**,July 1,Memphis Grizzlies,[103],NaN
2,Cristiano Felício (RFA),July 6,Chicago Bulls,[104],NaN
3,Danilo Gallinari*,Los Angeles Clippers(via sign and trade),Denver Nuggets,[61],NaN
4,Langston Galloway*,Detroit Pistons,Sacramento Kings,[105],NaN

In [8]:
FA2017 = FA2017[:225]

In [9]:
FA2017[0] = FA2017[0].str.replace('*','')
FA2017[0] = FA2017[0].str.replace('(RFA)','')
FA2017[0] = FA2017[0].str.replace(')','')
FA2017[0] = FA2017[0].str.replace('(','')
FA2017[0] = FA2017[0].str.replace('[','')
FA2017[0] = FA2017[0].str.replace('v]','')
FA2017[0] = FA2017[0].str.replace('e]','')
FA2017[0] = FA2017[0].str.replace('P. J.', 'P.J.')
FA2017[0] = FA2017[0].str.replace('J. J.', 'J.J.')
FA2017[0] = FA2017[0].str.replace('C. J.', 'C.J.')
FA2017[0] = FA2017[0].str.replace('K. J.', 'K.J.')
FA2017[0] = FA2017[0].str.replace('L. J.', 'L.J.')
FA2017[0] = FA2017[0].str.replace('V. J.', 'V.J.')
FA2017[0] = FA2017[0].str.replace('ć', 'c')
FA2017[0] = FA2017[0].str.replace('ê', 'e')
FA2017[0] = FA2017[0].str.replace('í', 'i')
FA2017[0] = FA2017[0].str.replace('š', 's')
FA2017[0] = FA2017[0].str.replace('é', 'e')
FA2017[0] = FA2017[0].str.replace('İ', 'I')
FA2017[0] = FA2017[0].str.replace('ž', 'z')
FA2017[0] = FA2017[0].str.replace('ó','o')

In [10]:
FA2017 = FA2017[FA2017[2].str.contains('undrafted') == False]
FA2017 = FA2017[FA2017[2].str.contains('D-League') == False]
FA2017 = FA2017[FA2017[2].str.contains('Spain') == False]
FA2017 = FA2017[FA2017[2].str.contains('Argentina') == False]
FA2017 = FA2017[FA2017[2].str.contains('Russia') == False]
FA2017 = FA2017[FA2017[2].str.contains('China') == False]
FA2017 = FA2017[FA2017[2].str.contains('Greece') == False]
FA2017 = FA2017[FA2017[2].str.contains('Israel') == False]
FA2017 = FA2017[FA2017[2].str.contains('G League') == False]
FA2017 = FA2017[FA2017[2].str.contains('Italy') == False]
FA2017 = FA2017[FA2017[2].str.contains('Philippines') == False]
FA2017 = FA2017[FA2017[2].str.contains('France') == False]
FA2017 = FA2017[FA2017[2].str.contains('Turkey') == False]
FA2017 = FA2017[FA2017[2].str.contains('Germany') == False]

In [11]:
FA2017 = FA2017[0]

In [12]:
FA2017.to_csv('2017_Free_Agents.csv', index=False)

# 2016 Free Agent Scraping

In [13]:
html = wp.page("List of 2016–17 NBA season transactions").html().encode("UTF-8")
FA2016 = pd.read_html(html)[5]
FA2016.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Tony Wroten[e],June 24,Memphis Grizzlies(claimed off waivers),New York Knicks(waived on June 12),[84][141]
2,Shawn Long[e],July 3,Philadelphia 76ers,LouisianaâLafayette(undrafted in 2016),[84][142]
3,James Webb III[e],Philadelphia 76ers,Boise State(undrafted in 2016),[84][142],NaN
4,D. J. Augustin,July 7,Orlando Magic,Denver Nuggets,[143]

In [14]:
FA2016 = FA2016[:233]

In [15]:
FA2016[0] = FA2016[0].str.replace('*','')
FA2016[0] = FA2016[0].str.replace('(RFA)','')
FA2016[0] = FA2016[0].str.replace(')','')
FA2016[0] = FA2016[0].str.replace('(','')
FA2016[0] = FA2016[0].str.replace('[','')
FA2016[0] = FA2016[0].str.replace('v]','')
FA2016[0] = FA2016[0].str.replace('e]','')
FA2016[0] = FA2016[0].str.replace('x]','')
FA2016[0] = FA2016[0].str.replace('aa]','')
FA2016[0] = FA2016[0].str.replace(']','')
FA2016[0] = FA2016[0].str.replace('P. J.', 'P.J.')
FA2016[0] = FA2016[0].str.replace('J. J.', 'J.J.')
FA2016[0] = FA2016[0].str.replace('C. J.', 'C.J.')
FA2016[0] = FA2016[0].str.replace('K. J.', 'K.J.')
FA2016[0] = FA2016[0].str.replace('L. J.', 'L.J.')
FA2016[0] = FA2016[0].str.replace('V. J.', 'V.J.')
FA2016[0] = FA2016[0].str.replace('J. P.', 'J.P.')
FA2016[0] = FA2016[0].str.replace('D. J.', 'D.J.')
FA2016[0] = FA2016[0].str.replace('ć', 'c')
FA2016[0] = FA2016[0].str.replace('ê', 'e')
FA2016[0] = FA2016[0].str.replace('í', 'i')
FA2016[0] = FA2016[0].str.replace('š', 's')
FA2016[0] = FA2016[0].str.replace('é', 'e')
FA2016[0] = FA2016[0].str.replace('İ', 'I')
FA2016[0] = FA2016[0].str.replace('ž', 'z')
FA2016[0] = FA2016[0].str.replace('ó', 'o')

FA2016[0] = FA2016[0].str.replace('Ä', 'A')
FA2016[0] = FA2016[0].str.replace('Ã¡', 'A')
FA2016[0] = FA2016[0].str.replace('Ã³', 'i')
FA2016[0] = FA2016[0].str.replace('Ãª', 'e')
FA2016[0] = FA2016[0].str.replace('Ã£o', 'ao')
FA2016[0] = FA2016[0].str.replace('AiA', 'cic')
FA2016[0] = FA2016[0].str.replace('Ã­', 'i')
FA2016[0] = FA2016[0].str.replace('A', 'c')

In [16]:
FA2016 = FA2016[FA2016[2].str.contains('undrafted') == False]
FA2016 = FA2016[FA2016[2].str.contains('D-League') == False]
FA2016 = FA2016[FA2016[2].str.contains('Spain') == False]
FA2016 = FA2016[FA2016[2].str.contains('Argentina') == False]
FA2016 = FA2016[FA2016[2].str.contains('Russia') == False]
FA2016 = FA2016[FA2016[2].str.contains('China') == False]
FA2016 = FA2016[FA2016[2].str.contains('Greece') == False]
FA2016 = FA2016[FA2016[2].str.contains('Israel') == False]

In [17]:
FA2016 = FA2016[0]

In [18]:
FA2016

0                    Player
1               Tony Wroten
2                Shawn Long
4             D.J. Augustin
5               Matt Barnes
6             Nicolas Batum
7             Kent Bazemore
8           Bismack Biyombo
9          Jordan Clarkson
10     Matthew Dellavedova
11                Luol Deng
12             Kevin Durant
13             Festus Ezeli
14           Evan Fournier
15               Jeff Green
16              Roy Hibbert
17           Wesley Johnson
18                Jon Leuer
19               Jeremy Lin
20              Ian Mahinmi
21         Luc Mbah a Moute
23         Andrew Nicholson
25         Chandler Parsons
27            Brian Roberts
28              Rajon Rondo
29             Brandon Rush
30           Ramon Sessions
31                Ish Smith
32              Jason Smith
33          Mirza Teletovic
34              Evan Turner
35         Hassan Whiteside
36            Arron Afflalo
37           Darrell Arthur
38         Harrison Barnes
39            Trevor Booker
40                Ian Clark
41           Jamal Crawford
42             Jared Dudley
44               Al Horford
45         Brandon Jennings
46              Joe Johnson
47             Courtney Lee
48           Timofey Mozgov
49              Joakim Noah
50           Dwight Powell
51            Austin Rivers
52           Garrett Temple
53             Lance Thomas
54           Deron Williams
55            Ryan Anderson
56              Eric Gordon
57         Gerald Henderson
58             Al Jefferson
60         Anthony Tolliver
61               David West
62          Wayne Ellington
63            Udonis Haslem
64            James Johnson
65          Meyers Leonard
66         Derrick Williams
67          Marvin Williams
68          Justin Hamilton
69             Cole Aldrich
70           Jerryd Bayless
71            Troy Daniels
72            Dwight Howard
74        Boban Marjanovic
75            Zaza Pachulia
77        Marreese Speights
78            Allen Crabbe
79              James Ennis
80           Tyler Johnson
81     James Michael McAdoo
83              Willie Reed
84               Luis Scola
85          Greivis VAsquez
86         Ryan Arcidiacono
87          Anthony Bennett
89          Mike Conley Jr.
90           Dewayne Dedmon
92            DeMar DeRozan
94               Randy Foye
95                Pau Gasol
96            Manu Ginibili
97           Kris Humphries
98             Jarrett Jack
99          Lamar Patterson
100         Jared Sullinger
101           Sasha Vujacic
102          Christian Wood
103           Matt Costello
104              Seth Curry
105         Andre Drummond
107             Dwyane Wade
109           Fred VanVleet
110        Anderson Varejao
111         Leandro Barbosa
112            Brandon Bass
113              Joe Harris
114             Jordan Hill
115                    Nene
116              Quincy Acy
117           Isaiah Canaan
119             Mike Miller
120          Chris Andersen
121            Aaron Brooks
122       Langston Galloway
123            Solomon Hill
124           E'Twaun Moore
126            Yogi Ferrell
127            Tim Frazier
128              Alonzo Gee
129          Terrence Jones
131         Marcus Thornton
132       Sheldon McClellan
133           Dirk Nowitzki
134              Beau Beech
135          Raymond Felton
136        Ray McCallum Jr.
139            Dion Waiters
140           Bradley Beal
144       Amar'e Stoudemire
147            Gerald Green
148       Maurice Harkless
152           Tyler Zeller
153       Spencer Dinwiddie
154       Richard Jefferson
155          Pablo Prigioni
156               Ron Baker
158             J.P. Tokoto
159           Alan Anderson
161             James Jones
162               David Lee
164          Miles Plumlee
165          Chasson Randle
166         Marcelo Huertas
167             Tony Wroten
168            Shawn Dawson
171            LeBron James
172          Chris Copeland
173            Ronnie Price
174            Robert Sacre
175           Grant Jerrett
176            D.J. Kennedy
178     Marcus Georges-Hunt
179              Beno Udrih
180            Toure' Murry
181             Jason Terry
182            Tarik Black
183          John Lucas III
184            Julyan Stone
185            Zach Auguste
186             Steve Novak
188               Ty Lawson
189          Anthony Barber
190           Julian Jacobs
192             Quincy Ford
196          Andrew Andrews
197             Elton Brand
198           Robbie Hummel
202         Cliff Alexander
203          Branden Dawson
205            Kevin Murphy
206           Arinze Onuaku
207           Damjan RudeÅ¾
208         Kevin SÃ©raphin
209            Xavier Henry
210           Ryan Richards
211              Elgin Cook
215            JaVale McGee
217           Greg Stiemsma
218            Nate Wolters
219           Jordan Farmar
222        Lance Stephenson
223            Trey Freeman
226            Vince Hunter
227            Lou Amundson
228              J.J. Avila
229           C.J. Williams
230              Will Bynum
231            Brady Heslip
232              Ryan Kelly
Name: 0, dtype: object

In [19]:
FA2016.to_csv('2016_Free_Agents.csv', index=False)

# 2015 Free Agents

In [20]:
html = wp.page("List of 2015–16 NBA season transactions").html().encode("UTF-8")
FA2015 = pd.read_html(html)[6]
FA2015.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Ryan Boatright,July 2,Brooklyn Nets,Connecticut(went undrafted in the 2015 Draft),[96]
2,Arron Afflalo,July 9,New York Knicks,Portland Trail Blazers,[64]
3,Alexis AjinÃ§a,New Orleans Pelicans,[97],NaN,NaN
4,LaMarcus Aldridge,San Antonio Spurs,Portland Trail Blazers,[98],NaN

In [21]:
FA2015 = FA2015[:257]

In [22]:
FA2015[0] = FA2015[0].str.replace('*','')
FA2015[0] = FA2015[0].str.replace('(RFA)','')
FA2015[0] = FA2015[0].str.replace(')','')
FA2015[0] = FA2015[0].str.replace('(','')
FA2015[0] = FA2015[0].str.replace('[','')
FA2015[0] = FA2015[0].str.replace('v]','')
FA2015[0] = FA2015[0].str.replace('e]','')
FA2015[0] = FA2015[0].str.replace('x]','')
FA2015[0] = FA2015[0].str.replace('aa]','')
FA2015[0] = FA2015[0].str.replace(']','')
FA2015[0] = FA2015[0].str.replace('P. J.', 'P.J.')
FA2015[0] = FA2015[0].str.replace('J. J.', 'J.J.')
FA2015[0] = FA2015[0].str.replace('C. J.', 'C.J.')
FA2015[0] = FA2015[0].str.replace('K. J.', 'K.J.')
FA2015[0] = FA2015[0].str.replace('L. J.', 'L.J.')
FA2015[0] = FA2015[0].str.replace('V. J.', 'V.J.')
FA2015[0] = FA2015[0].str.replace('J. P.', 'J.P.')
FA2015[0] = FA2015[0].str.replace('D. J.', 'D.J.')
FA2015[0] = FA2015[0].str.replace('J. R.', 'J.R.')
FA2015[0] = FA2015[0].str.replace('T. J.', 'T.J.')
FA2015[0] = FA2015[0].str.replace('ć', 'c')
FA2015[0] = FA2015[0].str.replace('ê', 'e')
FA2015[0] = FA2015[0].str.replace('í', 'i')
FA2015[0] = FA2015[0].str.replace('š', 's')
FA2015[0] = FA2015[0].str.replace('é', 'e')
FA2015[0] = FA2015[0].str.replace('İ', 'I')
FA2015[0] = FA2015[0].str.replace('ž', 'z')
FA2015[0] = FA2015[0].str.replace('ó', 'o')

FA2015[0] = FA2015[0].str.replace('Ã©', 'e')
FA2015[0] = FA2015[0].str.replace('Ã³', 'o')
FA2015[0] = FA2015[0].str.replace('Ä', 'c')
FA2015[0] = FA2015[0].str.replace('Ã§', 'c')
FA2015[0] = FA2015[0].str.replace('Ã', 'O')
FA2015[0] = FA2015[0].str.replace('ÅÄ±', 'si')

In [23]:
FA2015 = FA2015[FA2015[2].str.contains('undrafted') == False]
FA2015 = FA2015[FA2015[2].str.contains('D-League') == False]
FA2015 = FA2015[FA2015[2].str.contains('Spain') == False]
FA2015 = FA2015[FA2015[2].str.contains('Argentina') == False]
FA2015 = FA2015[FA2015[2].str.contains('Russia') == False]
FA2015 = FA2015[FA2015[2].str.contains('China') == False]
FA2015 = FA2015[FA2015[2].str.contains('Greece') == False]
FA2015 = FA2015[FA2015[2].str.contains('Israel') == False]
FA2015 = FA2015[FA2015[2].str.contains('G League') == False]
FA2015 = FA2015[FA2015[2].str.contains('Italy') == False]
FA2015 = FA2015[FA2015[2].str.contains('Philippines') == False]
FA2015 = FA2015[FA2015[2].str.contains('France') == False]
FA2015 = FA2015[FA2015[2].str.contains('Turkey') == False]
FA2015 = FA2015[FA2015[2].str.contains('Germany') == False]
FA2015 = FA2015[FA2015[2].str.contains('Estonia') == False]
FA2015 = FA2015[FA2015[2].str.contains('Hungary') == False]
FA2015 = FA2015[FA2015[2].str.contains('Dominican Republic') == False]
FA2015 = FA2015[FA2015[2].str.contains('Puerto Rico') == False]
FA2015 = FA2015[FA2015[2].str.contains('Lebanon') == False]
FA2015 = FA2015[FA2015[2].str.contains('Australia') == False]
FA2015 = FA2015[FA2015[2].str.contains('Iraq') == False]
FA2015 = FA2015[FA2015[2].str.contains('Slovenia') == False]
FA2015 = FA2015[FA2015[2].str.contains('Belgium') == False]
FA2015 = FA2015[FA2015[2].str.contains('Serbia') == False]
FA2015 = FA2015[FA2015[2].str.contains('Brazil') == False]

In [24]:
FA2015 = FA2015[0]

In [25]:
FA2015

0                     Player
1             Ryan Boatright
2              Arron Afflalo
3              Alexis Ajinca
4          LaMarcus Aldridge
5            Al-Farouq Aminu
6                  Omer Asik
7               Brandon Bass
8          Patrick Beverley
9              Jimmy Butler
10           DeMarre Carroll
11            Tyson Chandler
12          Dante Cunningham
13                  Ed Davis
14              Goran Dragic
15                Tim Duncan
16           Draymond Green
17              Gerald Green
18            Justin Holiday
19             Jonas Jerebko
20              Amir Johnson
21            Wesley Johnson
22            DeAndre Jordan
23               Cory Joseph
24              Shane Larkin
25                Jeremy Lin
26               Brook Lopez
27               Robin Lopez
28                Kevin Love
29           Wesley Matthews
30          Khris Middleton
31              Paul Millsap
32               Greg Monroe
33                 Gary Neal
34             Kyle O'Quinn
36           Thomas Robinson
37            Iman Shumpert
38             Kyle Singler
39               C.J. Watson
40          Derrick Williams
41            Louis Williams
42            Brandan Wright
43            Thaddeus Young
44           Wayne Ellington
45             Kevin Garnett
46               Joe Ingles
47              LeBron James
48               Paul Pierce
49         Amar'e Stoudemire
50              Lance Thomas
51               Dwyane Wade
52               Mo Williams
53        Luis David Montero
54             Alan Anderson
55               Aron Baynes
57              Enes Kanter
58              Cole Aldrich
59           Leandro Barbosa
60           Marco Belinelli
61                Marc Gasol
62               Drew Gooden
63              Kosta Koufos
64             Austin Rivers
65               Rajon Rondo
66              Corey Brewer
67              Aaron Brooks
68               Omri Casspi
69             Mike Dunleavy
70               Monta Ellis
71               Danny Green
72            Tobias Harris
74               Jordan Hill
75               Jason Smith
76            Deron Williams
77               Matt Bonner
78            Pierre Jackson
79                Luis Scola
80            James Anderson
81           Jose Juan Barea
82                Alonzo Gee
83            Kawhi Leonard
84                Josh Smith
85           Andrea Bargnani
86           Brandon Knight
88              Ronnie Price
89          Mirza Teletovic
91                David West
92           Bismack Biyombo
93              Joel Anthony
94              Luke Babbitt
95             Manu Ginobili
96           Reggie Jackson
97           K.J. McDaniels
99            Rodney Stuckey
100               Quincy Acy
103          Jimmer Fredette
104         Tyler Hansbrough
106             Caron Butler
111          Cliff Alexander
113             John Jenkins
115             Phil Pressey
117              James Jones
118          Marcus Thornton
119              Lavoy Allen
121             Jae Crowder
122     Matthew Dellavedova
123           Glenn Robinson
124       Shayne Whittington
126         Kendrick Perkins
128           Chris Copeland
129             Lou Amundson
131             Jeremy Evans
132             Andre Miller
133              Melvin Ejim
134           Pablo Prigioni
135        Richard Jefferson
136         Samuel Dalembert
137           Kevin Seraphin
138       Charlie Villanueva
139           Darrell Arthur
140             Will Barton
141            Jameer Nelson
143             Donald Sloan
144            Toney Douglas
145          Jonathan Holmes
146             JaVale McGee
147           Treveon Graham
149         Jason Richardson
150       Bryce Dejean-Jones
151          Tayshaun Prince
152            Corey Hawkins
154              Jason Terry
155              Jeff Withey
156             Keith Benson
158             J.J. O'Brien
159              Chuck Hayes
160               J.R. Smith
161         Greg Whittington
162               Remi Yusuf
163          Marcelo Huertas
165         Kendall Marshall
166            Eric Moreland
167            Darion Atkins
168            Dahntay Jones
171            Robert Upshaw
172                C.J. Fair
175            Deonte Burton
176      Patrick Christopher
178           Cory Jefferson
179               Henry Sims
181             Norris Cole
182            Justin Harper
186              Josh Powell
189            Will Cummings
193           DaJuan Summers
195              Jeff Adrien
197    Chris Douglas-Roberts
199            Keith Appling
202            Greg Stiemsma
204              Earl Barron
205                Ian Clark
212        Luc Mbah a Mouted
218                Ish Smith
226           T.J. McConnell
228            Jake Anderson
230          Anthony Bennett
231            Rasual Butler
235              Austin Daye
238               Ben Gordon
240             Ryan Hollins
246               John Lucas
256           Michael Qualls
Name: 0, dtype: object

In [26]:
FA2015.to_csv('2015_Free_Agents.csv', index=False)

# 2014 Free Agents

In [27]:
html = wp.page("List of 2014–15 NBA season transactions").html().encode("UTF-8")
FA2014 = pd.read_html(html)[5]
FA2014.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Willie Green,June 30,Orlando Magic(claimed off waivers),Los Angeles Clippers(waived on June 29),[110]
2,Shayne Whittington,July 2,Indiana Pacers,Western Michigan(went undrafted in the 2014 Dr...,[111]
3,Bryce Cotton,July 7,San Antonio Spurs,Providence(went undrafted in the 2014 Draft),[112]
4,Steve Blake,July 10,Portland Trail Blazers,Golden State Warriors,[113]

In [28]:
FA2014 = FA2014[:233]

In [29]:
FA2014[0] = FA2014[0].str.replace('*','')
FA2014[0] = FA2014[0].str.replace('(RFA)','')
FA2014[0] = FA2014[0].str.replace(')','')
FA2014[0] = FA2014[0].str.replace('(','')
FA2014[0] = FA2014[0].str.replace('[','')
FA2014[0] = FA2014[0].str.replace('v]','')
FA2014[0] = FA2014[0].str.replace('e]','')
FA2014[0] = FA2014[0].str.replace('x]','')
FA2014[0] = FA2014[0].str.replace('aa]','')
FA2014[0] = FA2014[0].str.replace(']','')
FA2014[0] = FA2014[0].str.replace('P. J.', 'P.J.')
FA2014[0] = FA2014[0].str.replace('J. J.', 'J.J.')
FA2014[0] = FA2014[0].str.replace('C. J.', 'C.J.')
FA2014[0] = FA2014[0].str.replace('K. J.', 'K.J.')
FA2014[0] = FA2014[0].str.replace('L. J.', 'L.J.')
FA2014[0] = FA2014[0].str.replace('V. J.', 'V.J.')
FA2014[0] = FA2014[0].str.replace('J. P.', 'J.P.')
FA2014[0] = FA2014[0].str.replace('D. J.', 'D.J.')
FA2014[0] = FA2014[0].str.replace('J. R.', 'J.R.')
FA2014[0] = FA2014[0].str.replace('T. J.', 'T.J.')
FA2014[0] = FA2014[0].str.replace('A. J.', 'A.J.')
FA2014[0] = FA2014[0].str.replace('ć', 'c')
FA2014[0] = FA2014[0].str.replace('ê', 'e')
FA2014[0] = FA2014[0].str.replace('í', 'i')
FA2014[0] = FA2014[0].str.replace('š', 's')
FA2014[0] = FA2014[0].str.replace('é', 'e')
FA2014[0] = FA2014[0].str.replace('İ', 'I')
FA2014[0] = FA2014[0].str.replace('ž', 'z')
FA2014[0] = FA2014[0].str.replace('ó', 'o')
FA2014[0] = FA2014[0].str.replace('á', 'a')
FA2014[0] = FA2014[0].str.replace('ü', 'u')
FA2014[0] = FA2014[0].str.replace('ğ', 'g')

FA2014[0] = FA2014[0].str.replace('P.ice', ' Price')

In [30]:
FA2014 = FA2014[FA2014[2].str.contains('undrafted') == False]
FA2014 = FA2014[FA2014[2].str.contains('D-League') == False]
FA2014 = FA2014[FA2014[2].str.contains('Spain') == False]
FA2014 = FA2014[FA2014[2].str.contains('Argentina') == False]
FA2014 = FA2014[FA2014[2].str.contains('Russia') == False]
FA2014 = FA2014[FA2014[2].str.contains('China') == False]
FA2014 = FA2014[FA2014[2].str.contains('Greece') == False]
FA2014 = FA2014[FA2014[2].str.contains('Israel') == False]
FA2014 = FA2014[FA2014[2].str.contains('G League') == False]
FA2014 = FA2014[FA2014[2].str.contains('Italy') == False]
FA2014 = FA2014[FA2014[2].str.contains('Philippines') == False]
FA2014 = FA2014[FA2014[2].str.contains('France') == False]
FA2014 = FA2014[FA2014[2].str.contains('Turkey') == False]
FA2014 = FA2014[FA2014[2].str.contains('Germany') == False]
FA2014 = FA2014[FA2014[2].str.contains('Estonia') == False]
FA2014 = FA2014[FA2014[2].str.contains('Hungary') == False]
FA2014 = FA2014[FA2014[2].str.contains('Dominican Republic') == False]
FA2014 = FA2014[FA2014[2].str.contains('Puerto Rico') == False]
FA2014 = FA2014[FA2014[2].str.contains('Lebanon') == False]
FA2014 = FA2014[FA2014[2].str.contains('Australia') == False]
FA2014 = FA2014[FA2014[2].str.contains('Iraq') == False]
FA2014 = FA2014[FA2014[2].str.contains('Slovenia') == False]
FA2014 = FA2014[FA2014[2].str.contains('Belgium') == False]
FA2014 = FA2014[FA2014[2].str.contains('Serbia') == False]
FA2014 = FA2014[FA2014[2].str.contains('Brazil') == False]
FA2014 = FA2014[FA2014[2].str.contains('Venezuela') == False]

In [31]:
FA2014 = FA2014[0]

In [32]:
FA2014.to_csv('2014_Free_Agents.csv', index=False)

# 2013 Free Agents

In [33]:
html = wp.page("List of 2013–14 NBA season transactions").html().encode("UTF-8")
FA2013 = pd.read_html(html)[7]
FA2013.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Donald Sloan,July 3,Indiana Pacers,Guangdong Southern Tigers (China),[101]
2,Al-Farouq Aminu,July 10,New Orleans Pelicans,[102],NaN
3,Chris Andersen,Miami Heat,[103],NaN,NaN
4,Matt Barnes,Los Angeles Clippers,[104],NaN,NaN

In [34]:
FA2013 = FA2013[:260]

In [35]:
FA2013[0] = FA2013[0].str.replace('*','')
FA2013[0] = FA2013[0].str.replace('(RFA)','')
FA2013[0] = FA2013[0].str.replace(')','')
FA2013[0] = FA2013[0].str.replace('(','')
FA2013[0] = FA2013[0].str.replace('[','')
FA2013[0] = FA2013[0].str.replace('v]','')
FA2013[0] = FA2013[0].str.replace('e]','')
FA2013[0] = FA2013[0].str.replace('x]','')
FA2013[0] = FA2013[0].str.replace('aa]','')
FA2013[0] = FA2013[0].str.replace(']','')
FA2013[0] = FA2013[0].str.replace('P. J.', 'P.J.')
FA2013[0] = FA2013[0].str.replace('J. J.', 'J.J.')
FA2013[0] = FA2013[0].str.replace('C. J.', 'C.J.')
FA2013[0] = FA2013[0].str.replace('K. J.', 'K.J.')
FA2013[0] = FA2013[0].str.replace('L. J.', 'L.J.')
FA2013[0] = FA2013[0].str.replace('V. J.', 'V.J.')
FA2013[0] = FA2013[0].str.replace('J. P.', 'J.P.')
FA2013[0] = FA2013[0].str.replace('D. J.', 'D.J.')
FA2013[0] = FA2013[0].str.replace('J. R.', 'J.R.')
FA2013[0] = FA2013[0].str.replace('T. J.', 'T.J.')
FA2013[0] = FA2013[0].str.replace('A. J.', 'A.J.')
FA2013[0] = FA2013[0].str.replace('O. J.', 'O.J.')
FA2013[0] = FA2013[0].str.replace('ć', 'c')
FA2013[0] = FA2013[0].str.replace('ê', 'e')
FA2013[0] = FA2013[0].str.replace('í', 'i')
FA2013[0] = FA2013[0].str.replace('š', 's')
FA2013[0] = FA2013[0].str.replace('é', 'e')
FA2013[0] = FA2013[0].str.replace('İ', 'I')
FA2013[0] = FA2013[0].str.replace('ž', 'z')
FA2013[0] = FA2013[0].str.replace('ó', 'o')
FA2013[0] = FA2013[0].str.replace('á', 'a')
FA2013[0] = FA2013[0].str.replace('ü', 'u')
FA2013[0] = FA2013[0].str.replace('ğ', 'g')

FA2013[0] = FA2013[0].str.replace('P.ice', ' Price')
FA2013[0] = FA2013[0].str.replace('R.dick', ' Redick')
FA2013[0] = FA2013[0].str.replace('A.J.fferson', 'Al Jefferson')

In [36]:
FA2013 = FA2013[FA2013[2].str.contains('undrafted') == False]
FA2013 = FA2013[FA2013[2].str.contains('D-League') == False]
FA2013 = FA2013[FA2013[2].str.contains('Spain') == False]
FA2013 = FA2013[FA2013[2].str.contains('Argentina') == False]
FA2013 = FA2013[FA2013[2].str.contains('Russia') == False]
FA2013 = FA2013[FA2013[2].str.contains('China') == False]
FA2013 = FA2013[FA2013[2].str.contains('Greece') == False]
FA2013 = FA2013[FA2013[2].str.contains('Israel') == False]
FA2013 = FA2013[FA2013[2].str.contains('G League') == False]
FA2013 = FA2013[FA2013[2].str.contains('Italy') == False]
FA2013 = FA2013[FA2013[2].str.contains('Philippines') == False]
FA2013 = FA2013[FA2013[2].str.contains('France') == False]
FA2013 = FA2013[FA2013[2].str.contains('Turkey') == False]
FA2013 = FA2013[FA2013[2].str.contains('Germany') == False]
FA2013 = FA2013[FA2013[2].str.contains('Estonia') == False]
FA2013 = FA2013[FA2013[2].str.contains('Hungary') == False]
FA2013 = FA2013[FA2013[2].str.contains('Dominican Republic') == False]
FA2013 = FA2013[FA2013[2].str.contains('Puerto Rico') == False]
FA2013 = FA2013[FA2013[2].str.contains('Lebanon') == False]
FA2013 = FA2013[FA2013[2].str.contains('Australia') == False]
FA2013 = FA2013[FA2013[2].str.contains('Iraq') == False]
FA2013 = FA2013[FA2013[2].str.contains('Slovenia') == False]
FA2013 = FA2013[FA2013[2].str.contains('Belgium') == False]
FA2013 = FA2013[FA2013[2].str.contains('Serbia') == False]
FA2013 = FA2013[FA2013[2].str.contains('Brazil') == False]
FA2013 = FA2013[FA2013[2].str.contains('Venezuela') == False]
FA2013 = FA2013[FA2013[2].str.contains('Lithuania') == False]
FA2013 = FA2013[FA2013[2].str.contains('Ukraine') == False]
FA2013 = FA2013[FA2013[2].str.contains('Japan') == False]
FA2013 = FA2013[FA2013[2].str.contains('ABA') == False]
FA2013 = FA2013[FA2013[2].str.contains('Bulgaria') == False]
FA2013 = FA2013[FA2013[2].str.contains('PBL') == False]
FA2013 = FA2013[FA2013[2].str.contains('Latvia') == False]

In [37]:
FA2013 = FA2013[0]

In [38]:
FA2013.to_csv('2013_Free_Agents.csv', index=False)

# 2012 Free Agents

In [39]:
html = wp.page("List of 2012–13 NBA season transactions").html().encode("UTF-8")
FA2012 = pd.read_html(html)[5]
FA2012.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Lavoy Allen (RFA),July 11,Philadelphia 76ers,[77],NaN
2,Ray Allen,Miami Heat,Boston Celtics,[77],NaN
3,Ryan Anderson (RFA),New Orleans Hornets(via sign and trade),Orlando Magic,[77],NaN
4,Marcus Camby,New York Knicks(via sign and trade),Houston Rockets,[77],NaN

In [40]:
FA2012 = FA2012[:269]

In [41]:
FA2012[0] = FA2012[0].str.replace('*','')
FA2012[0] = FA2012[0].str.replace('(RFA)','')
FA2012[0] = FA2012[0].str.replace(')','')
FA2012[0] = FA2012[0].str.replace('(','')
FA2012[0] = FA2012[0].str.replace('[','')
FA2012[0] = FA2012[0].str.replace('v]','')
FA2012[0] = FA2012[0].str.replace('e]','')
FA2012[0] = FA2012[0].str.replace('x]','')
FA2012[0] = FA2012[0].str.replace('aa]','')
FA2012[0] = FA2012[0].str.replace(']','')
FA2012[0] = FA2012[0].str.replace('P. J.', 'P.J.')
FA2012[0] = FA2012[0].str.replace('J. J.', 'J.J.')
FA2012[0] = FA2012[0].str.replace('C. J.', 'C.J.')
FA2012[0] = FA2012[0].str.replace('K. J.', 'K.J.')
FA2012[0] = FA2012[0].str.replace('L. J.', 'L.J.')
FA2012[0] = FA2012[0].str.replace('V. J.', 'V.J.')
FA2012[0] = FA2012[0].str.replace('J. P.', 'J.P.')
FA2012[0] = FA2012[0].str.replace('D. J.', 'D.J.')
FA2012[0] = FA2012[0].str.replace('J. R.', 'J.R.')
FA2012[0] = FA2012[0].str.replace('T. J.', 'T.J.')
FA2012[0] = FA2012[0].str.replace('A. J.', 'A.J.')
FA2012[0] = FA2012[0].str.replace('O. J.', 'O.J.')
FA2012[0] = FA2012[0].str.replace('ć', 'c')
FA2012[0] = FA2012[0].str.replace('ê', 'e')
FA2012[0] = FA2012[0].str.replace('í', 'i')
FA2012[0] = FA2012[0].str.replace('š', 's')
FA2012[0] = FA2012[0].str.replace('é', 'e')
FA2012[0] = FA2012[0].str.replace('İ', 'I')
FA2012[0] = FA2012[0].str.replace('ž', 'z')
FA2012[0] = FA2012[0].str.replace('ó', 'o')
FA2012[0] = FA2012[0].str.replace('á', 'a')
FA2012[0] = FA2012[0].str.replace('ü', 'u')
FA2012[0] = FA2012[0].str.replace('ğ', 'g')
FA2012[0] = FA2012[0].str.replace(', Jr.', ' Jr.')



FA2012[0] = FA2012[0].str.replace('ÄiÄ', 'cic')
FA2012[0] = FA2012[0].str.replace('P.ice', ' Price')
FA2012[0] = FA2012[0].str.replace('Ã', 'O')
FA2012[0] = FA2012[0].str.replace('ÅÄ±', 'si')
FA2012[0] = FA2012[0].str.replace('Ä', 'c')
FA2012[0] = FA2012[0].str.replace('Ä°', 'I')

In [42]:
FA2012 = FA2012[FA2012[2].str.contains('undrafted') == False]
FA2012 = FA2012[FA2012[2].str.contains('D-League') == False]
FA2012 = FA2012[FA2012[2].str.contains('Spain') == False]
FA2012 = FA2012[FA2012[2].str.contains('Argentina') == False]
FA2012 = FA2012[FA2012[2].str.contains('Russia') == False]
FA2012 = FA2012[FA2012[2].str.contains('China') == False]
FA2012 = FA2012[FA2012[2].str.contains('Greece') == False]
FA2012 = FA2012[FA2012[2].str.contains('Israel') == False]
FA2012 = FA2012[FA2012[2].str.contains('G League') == False]
FA2012 = FA2012[FA2012[2].str.contains('Italy') == False]
FA2012 = FA2012[FA2012[2].str.contains('Philippines') == False]
FA2012 = FA2012[FA2012[2].str.contains('France') == False]
FA2012 = FA2012[FA2012[2].str.contains('Turkey') == False]
FA2012 = FA2012[FA2012[2].str.contains('Germany') == False]
FA2012 = FA2012[FA2012[2].str.contains('Estonia') == False]
FA2012 = FA2012[FA2012[2].str.contains('Hungary') == False]
FA2012 = FA2012[FA2012[2].str.contains('Dominican Republic') == False]
FA2012 = FA2012[FA2012[2].str.contains('Puerto Rico') == False]
FA2012 = FA2012[FA2012[2].str.contains('Lebanon') == False]
FA2012 = FA2012[FA2012[2].str.contains('Australia') == False]
FA2012 = FA2012[FA2012[2].str.contains('Iraq') == False]
FA2012 = FA2012[FA2012[2].str.contains('Slovenia') == False]
FA2012 = FA2012[FA2012[2].str.contains('Belgium') == False]
FA2012 = FA2012[FA2012[2].str.contains('Serbia') == False]
FA2012 = FA2012[FA2012[2].str.contains('Brazil') == False]
FA2012 = FA2012[FA2012[2].str.contains('Venezuela') == False]
FA2012 = FA2012[FA2012[2].str.contains('Lithuania') == False]
FA2012 = FA2012[FA2012[2].str.contains('Ukraine') == False]
FA2012 = FA2012[FA2012[2].str.contains('Japan') == False]
FA2012 = FA2012[FA2012[2].str.contains('ABA') == False]
FA2012 = FA2012[FA2012[2].str.contains('Bulgaria') == False]
FA2012 = FA2012[FA2012[2].str.contains('PBL') == False]
FA2012 = FA2012[FA2012[2].str.contains('Latvia') == False]
FA2012 = FA2012[FA2012[2].str.contains('New Zealand') == False]
FA2012 = FA2012[FA2012[2].str.contains('Romania') == False]
FA2012 = FA2012[FA2012[2].str.contains('Tunisia') == False]
FA2012 = FA2012[FA2012[2].str.contains('Poland') == False]
FA2012 = FA2012[FA2012[2].str.contains('Croatia') == False]
FA2012 = FA2012[FA2012[2].str.contains('Austria') == False]
FA2012 = FA2012[FA2012[2].str.contains('Czech Republic') == False]
FA2012 = FA2012[FA2012[2].str.contains('Retired') == False]

In [43]:
FA2012 = FA2012[0]

In [44]:
FA2012.to_csv('2012_Free_Agents.csv', index=False)

# 2011 Free Agents

In [45]:
html = wp.page("List of 2011–12 NBA season transactions").html().encode("UTF-8")
FA2011 = pd.read_html(html)[6]
FA2011.head()

,0,1,2,3,4
0,Player,Date signed,New team,Former team,Ref
1,Jason Collins,December 9,Atlanta Hawks,[79],NaN
2,Ivan Johnson,Atlanta Hawks,Qingdao DoubleStar (China),[79],NaN
3,Tracy McGrady,Atlanta Hawks,Detroit Pistons,[79],NaN
4,Vladimir RadmanoviÄ,Atlanta Hawks,Golden State Warriors,[80],NaN

In [46]:
FA2011 = FA2011[:122]

In [47]:
FA2011[0] = FA2011[0].str.replace('*','')
FA2011[0] = FA2011[0].str.replace('(RFA)','')
FA2011[0] = FA2011[0].str.replace(')','')
FA2011[0] = FA2011[0].str.replace('(','')
FA2011[0] = FA2011[0].str.replace('[','')
FA2011[0] = FA2011[0].str.replace('v]','')
FA2011[0] = FA2011[0].str.replace('e]','')
FA2011[0] = FA2011[0].str.replace('x]','')
FA2011[0] = FA2011[0].str.replace('aa]','')
FA2011[0] = FA2011[0].str.replace(']','')
FA2011[0] = FA2011[0].str.replace('P. J.', 'P.J.')
FA2011[0] = FA2011[0].str.replace('J. J.', 'J.J.')
FA2011[0] = FA2011[0].str.replace('C. J.', 'C.J.')
FA2011[0] = FA2011[0].str.replace('K. J.', 'K.J.')
FA2011[0] = FA2011[0].str.replace('L. J.', 'L.J.')
FA2011[0] = FA2011[0].str.replace('V. J.', 'V.J.')
FA2011[0] = FA2011[0].str.replace('J. P.', 'J.P.')
FA2011[0] = FA2011[0].str.replace('D. J.', 'D.J.')
FA2011[0] = FA2011[0].str.replace('J. R.', 'J.R.')
FA2011[0] = FA2011[0].str.replace('T. J.', 'T.J.')
FA2011[0] = FA2011[0].str.replace('A. J.', 'A.J.')
FA2011[0] = FA2011[0].str.replace('O. J.', 'O.J.')
FA2011[0] = FA2011[0].str.replace('ć', 'c')
FA2011[0] = FA2011[0].str.replace('ê', 'e')
FA2011[0] = FA2011[0].str.replace('í', 'i')
FA2011[0] = FA2011[0].str.replace('š', 's')
FA2011[0] = FA2011[0].str.replace('é', 'e')
FA2011[0] = FA2011[0].str.replace('İ', 'I')
FA2011[0] = FA2011[0].str.replace('ž', 'z')
FA2011[0] = FA2011[0].str.replace('ó', 'o')
FA2011[0] = FA2011[0].str.replace('á', 'a')
FA2011[0] = FA2011[0].str.replace('ü', 'u')
FA2011[0] = FA2011[0].str.replace('ğ', 'g')
FA2011[0] = FA2011[0].str.replace(', Jr.', ' Jr.')

FA2011[0] = FA2011[0].str.replace('Ä', 'c')
FA2011[0] = FA2011[0].str.replace('Ãª', 'e')
FA2011[0] = FA2011[0].str.replace('JosÃ© Juan', 'J.J.')
FA2011[0] = FA2011[0].str.replace('Ã«', 'e')
FA2011[0] = FA2011[0].str.replace('Ã©', 'e')

In [48]:
FA2011 = FA2011[FA2011[2].str.contains('undrafted') == False]
FA2011 = FA2011[FA2011[2].str.contains('D-League') == False]
FA2011 = FA2011[FA2011[2].str.contains('Spain') == False]
FA2011 = FA2011[FA2011[2].str.contains('Argentina') == False]
FA2011 = FA2011[FA2011[2].str.contains('Russia') == False]
FA2011 = FA2011[FA2011[2].str.contains('China') == False]
FA2011 = FA2011[FA2011[2].str.contains('Greece') == False]
FA2011 = FA2011[FA2011[2].str.contains('Israel') == False]
FA2011 = FA2011[FA2011[2].str.contains('G League') == False]
FA2011 = FA2011[FA2011[2].str.contains('Italy') == False]
FA2011 = FA2011[FA2011[2].str.contains('Philippines') == False]
FA2011 = FA2011[FA2011[2].str.contains('France') == False]
FA2011 = FA2011[FA2011[2].str.contains('Turkey') == False]
FA2011 = FA2011[FA2011[2].str.contains('Germany') == False]
FA2011 = FA2011[FA2011[2].str.contains('Estonia') == False]
FA2011 = FA2011[FA2011[2].str.contains('Hungary') == False]
FA2011 = FA2011[FA2011[2].str.contains('Dominican Republic') == False]
FA2011 = FA2011[FA2011[2].str.contains('Puerto Rico') == False]
FA2011 = FA2011[FA2011[2].str.contains('Lebanon') == False]
FA2011 = FA2011[FA2011[2].str.contains('Australia') == False]
FA2011 = FA2011[FA2011[2].str.contains('Iraq') == False]
FA2011 = FA2011[FA2011[2].str.contains('Slovenia') == False]
FA2011 = FA2011[FA2011[2].str.contains('Belgium') == False]
FA2011 = FA2011[FA2011[2].str.contains('Serbia') == False]
FA2011 = FA2011[FA2011[2].str.contains('Brazil') == False]
FA2011 = FA2011[FA2011[2].str.contains('Venezuela') == False]
FA2011 = FA2011[FA2011[2].str.contains('Lithuania') == False]
FA2011 = FA2011[FA2011[2].str.contains('Ukraine') == False]
FA2011 = FA2011[FA2011[2].str.contains('Japan') == False]
FA2011 = FA2011[FA2011[2].str.contains('ABA') == False]
FA2011 = FA2011[FA2011[2].str.contains('Bulgaria') == False]
FA2011 = FA2011[FA2011[2].str.contains('PBL') == False]
FA2011 = FA2011[FA2011[2].str.contains('Latvia') == False]
FA2011 = FA2011[FA2011[2].str.contains('New Zealand') == False]
FA2011 = FA2011[FA2011[2].str.contains('Romania') == False]
FA2011 = FA2011[FA2011[2].str.contains('Tunisia') == False]
FA2011 = FA2011[FA2011[2].str.contains('Poland') == False]
FA2011 = FA2011[FA2011[2].str.contains('Croatia') == False]
FA2011 = FA2011[FA2011[2].str.contains('Austria') == False]
FA2011 = FA2011[FA2011[2].str.contains('Czech Republic') == False]
FA2011 = FA2011[FA2011[2].str.contains('Retired') == False]
FA2011 = FA2011[FA2011[2].str.contains('None') == False]

In [49]:
FA2011 = FA2011[0]

In [50]:
FA2011.to_csv('2011_Free_Agents.csv', index=False)

# 2010 Free Agents

In [51]:
html = wp.page("List of 2010–11 NBA season transactions").html().encode("UTF-8")
FA2010 = pd.read_html(html)[5][1:]
FA2010.head()

               0                   1                     2            3
1         Player              Signed              New team  Former team
2  Channing Frye              July 8          Phoenix Suns          NaN
3    Chris Duhon       Orlando Magic       New York Knicks          NaN
4       Rudy Gay   Memphis Grizzlies                   NaN          NaN
5    Steve Blake  Los Angeles Lakers  Los Angeles Clippers          NaN

In [52]:
FA2010 = FA2010[:112]

In [53]:
FA2010[0] = FA2010[0].str.replace('*','')
FA2010[0] = FA2010[0].str.replace('(RFA)','')
FA2010[0] = FA2010[0].str.replace(')','')
FA2010[0] = FA2010[0].str.replace('(','')
FA2010[0] = FA2010[0].str.replace('[','')
FA2010[0] = FA2010[0].str.replace('v]','')
FA2010[0] = FA2010[0].str.replace('e]','')
FA2010[0] = FA2010[0].str.replace('x]','')
FA2010[0] = FA2010[0].str.replace('aa]','')
FA2010[0] = FA2010[0].str.replace(']','')
FA2010[0] = FA2010[0].str.replace('P. J.', 'P.J.')
FA2010[0] = FA2010[0].str.replace('J. J.', 'J.J.')
FA2010[0] = FA2010[0].str.replace('C. J.', 'C.J.')
FA2010[0] = FA2010[0].str.replace('K. J.', 'K.J.')
FA2010[0] = FA2010[0].str.replace('L. J.', 'L.J.')
FA2010[0] = FA2010[0].str.replace('V. J.', 'V.J.')
FA2010[0] = FA2010[0].str.replace('J. P.', 'J.P.')
FA2010[0] = FA2010[0].str.replace('D. J.', 'D.J.')
FA2010[0] = FA2010[0].str.replace('J. R.', 'J.R.')
FA2010[0] = FA2010[0].str.replace('T. J.', 'T.J.')
FA2010[0] = FA2010[0].str.replace('A. J.', 'A.J.')
FA2010[0] = FA2010[0].str.replace('O. J.', 'O.J.')
FA2010[0] = FA2010[0].str.replace('ć', 'c')
FA2010[0] = FA2010[0].str.replace('ê', 'e')
FA2010[0] = FA2010[0].str.replace('í', 'i')
FA2010[0] = FA2010[0].str.replace('š', 's')
FA2010[0] = FA2010[0].str.replace('é', 'e')
FA2010[0] = FA2010[0].str.replace('İ', 'I')
FA2010[0] = FA2010[0].str.replace('ž', 'z')
FA2010[0] = FA2010[0].str.replace('ó', 'o')
FA2010[0] = FA2010[0].str.replace('á', 'a')
FA2010[0] = FA2010[0].str.replace('ü', 'u')
FA2010[0] = FA2010[0].str.replace('ğ', 'g')
FA2010[0] = FA2010[0].str.replace(', Jr.', ' Jr.')
FA2010[0] = FA2010[0].str.replace('Ž', 'Z')
FA2010[0] = FA2010[0].str.replace('ū', 'u')

FA2010[0] = FA2010[0].str.replace('R.dick', ' Redick')

In [54]:
FA2010 = FA2010[0]

In [55]:
FA2010.to_csv('2010_Free_Agents.csv', index=False)

# 2009 Free Agents

In [56]:
html = wp.page("List of 2009–10 NBA season transactions").html().encode("UTF-8")
FA2009 = pd.read_html(html)[6][2:]
FA2009.head()

                 0                   1                2                   3
2             July                 NaN              NaN                 NaN
3     Trevor Ariza              July 8  Houston Rockets  Los Angeles Lakers
4       Ron Artest  Los Angeles Lakers  Houston Rockets                 NaN
5  Rasheed Wallace      Boston Celtics  Detroit Pistons                 NaN
6       Ben Gordon     Detroit Pistons    Chicago Bulls                 NaN

In [57]:
FA2009 = FA2009[:91]

In [58]:
FA2009[0] = FA2009[0].str.replace('ã', 'a')
FA2009[0] = FA2009[0].str.replace('İ', 'I')
FA2009[0] = FA2009[0].str.replace('ć', 'c')
FA2009[0] = FA2009[0].str.replace('ž', 'z')
FA2009[0] = FA2009[0].str.replace('C. J.', 'C.J.')

In [59]:
FA2009 = FA2009[FA2009[0] != 'August']
FA2009 = FA2009[FA2009[0] != 'September']

In [60]:
FA2009 = FA2009[0]

In [61]:
FA2009.to_csv('2009_Free_Agents.csv', index=False)

# 2008 Free Agents

In [62]:
html = wp.page("List of 2008–09 NBA season transactions").html().encode("UTF-8")
FA2008 = pd.read_html(html)[4]
FA2008.head()

              0                    1                 2                3
0        Player          Date signed          New team      Former team
1  Gerald Green               July 3  Dallas Mavericks  Houston Rockets
2  Hassan Adams               July 6   Toronto Raptors    Teramo Basket
3   J. J. Barea               July 9  Dallas Mavericks              NaN
4    Chris Paul  New Orleans Hornets               NaN              NaN

In [63]:
FA2008[0] = FA2008[0].str.replace('J. J.', 'J.J.')
FA2008[0] = FA2008[0].str.replace('é', 'e')
FA2008[0] = FA2008[0].str.replace('ó', 'o')
FA2008[0] = FA2008[0].str.replace('á', 'a')
FA2008[0] = FA2008[0].str.replace('ć', 'c')
FA2008[0] = FA2008[0].str.replace(', Jr.', ' Jr.')

In [64]:
FA2008 = FA2008[0]

In [65]:
FA2008.to_csv('2008_Free_Agents.csv', index=False)